# Generated by Django 3.0.4 on 2020-04-12 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200412_2046'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Accounts',
            new_name='Employees',
        ),
    ]
