# Generated by Django 3.0.4 on 2020-04-12 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200412_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='photo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='assets/%Y/%m/%d/'),
        ),
    ]
