# Generated by Django 3.0.4 on 2020-04-12 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200413_0116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='photo',
        ),
    ]
