# Generated by Django 3.0.4 on 2020-04-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_employees_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='department',
            field=models.CharField(choices=[('en', 'en'), ('kz', 'kz'), ('ru', 'ru')], default='en', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='position',
            field=models.CharField(choices=[('Teacher', 'Teacher'), ('Student', 'Student')], max_length=30, null=True),
        ),
    ]
