# Generated by Django 3.0.4 on 2020-04-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_devices'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='advisor',
            field=models.CharField(choices=[('Assem Talasbek', 'Assem Talasbek'), ('Nazim Ibragim', 'Nazim Ibragim')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=30, null=True),
        ),
    ]
