# Generated by Django 3.0.4 on 2020-04-18 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20200418_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='advisor',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
